# Generated by Django 2.1.7 on 2019-05-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20190523_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='setting',
            field=models.CharField(choices=[('empty', 'empty'), ('sample', 'sample'), ('main', 'main')], max_length=100),
        ),
    ]
