# Generated by Django 2.1.7 on 2019-05-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_page_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.PositiveIntegerField()),
                ('target', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
