# Generated by Django 2.1.7 on 2019-05-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0006_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='desc_color',
            field=models.CharField(default='#444444', max_length=20),
        ),
    ]
