# Generated by Django 2.1.7 on 2019-05-29 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='author',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None),
        ),
    ]
