# Generated by Django 2.1.7 on 2019-05-29 13:32

import blogger.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0009_page_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='source',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='link',
            name='target',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=blogger.models.admin, size=None),
        ),
    ]
