# Generated by Django 2.1.7 on 2019-05-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0010_auto_20190529_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='author',
            new_name='authors',
        ),
    ]
