# Generated by Django 2.1.7 on 2019-11-21 05:03

import blogger.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0011_auto_20190529_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=blogger.models.admin, size=None),
        ),
        migrations.AddField(
            model_name='link',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
